# defaultEntryPoints must be at the top because it should not be in any table below

defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "certs/traefik.crt"
      keyFile = "certs/traefik.key"

   [docker]
   endpoint = "unix:///var/run/docker.sock"
   domain = "sandcsw.com"
   watch = true
   exposedbydefault = false
