version: '2'


services:

  master-filebeat:
    extends:
      file: docker-compose.yml
      service: master-filebeat
    labels:
      - "traefik.enable=false"


  logstash:
    extends:
      file: docker-compose.yml
      service: logstash
    labels:
      - "traefik.enable=false"


  validate-logstash-config:
    extends:
      file: docker-compose.yml
      service: validate-logstash-config
    labels:
      - "traefik.enable=false"

  elasticsearch:
    extends:
      file: docker-compose.yml
      service: elasticsearch
    labels:
      - "traefik.enable=false"

  curator:
    extends:
      file: docker-compose.yml
      service: curator
    labels:
      - "traefik.enable=false"

  kibana:
    extends:
      file: docker-compose.yml
      service: kibana
    environment:
      - VIRTUAL_HOST=kibana.${DOMAIN}
      - LETSENCRYPT_HOST=kibana.${DOMAIN}
      - LETSENCRYPT_EMAIL=admin@${DOMAIN}
      - LETSENCRYPT_TEST=false
      - HTTPS_METHOD=nohttp
    labels:
      - "traefik.enable=false"

  # elastalert:
  #   extends:
  #     file: docker-compose.yml
  #     service: elastalert

networks:
  default:
    external:
      name: monitoring_logging
