version: '2'


services:

  master-nodeexporter:
    extends:
      file: docker-compose.yml
      service: master-nodeexporter
    labels:
      - "traefik.enable=false"

  master-cadvisor:
    extends:
      file: docker-compose.yml
      service: master-cadvisor
    labels:
      - "traefik.enable=false"

  prometheus:
    extends:
      file: docker-compose.yml
      service: prometheus
    labels:
      - "traefik.enable=true"
      - "traefik.backend=prometheus"
      - "traefik.frontend.rule=Host:prometheus.sandcsw.com"
      - "traefik.frontend.entryPoints=https"
      - "traefik.port=443"
      - "traefik.docker.network=monitoring_logging"


  grafana:
    extends:
      file: docker-compose.yml
      service: grafana
    labels:
      - "traefik.enable=true"
      - "traefik.backend=grafana"
      - "traefik.frontend.rule=Host:grafana.sandcsw.com"
      - "traefik.frontend.entryPoints=https"
      - "traefik.port=443"
      - "traefik.docker.network=monitoring_logging"

  alertmanager:
    extends:
      file: docker-compose.yml
      service: alertmanager
    labels:
      - "traefik.enable=true"
      - "traefik.backend=alertmanager"
      - "traefik.frontend.rule=Host:alertmanager.sandcsw.com"
      - "traefik.frontend.entryPoints=https"
      - "traefik.port=443"
      - "traefik.docker.network=monitoring_logging"

networks:
  default:
    external:
      name: monitoring_logging
