version: '2'


services:

  master-nodeexporter:
    extends:
      file: docker-compose.yml
      service: master-nodeexporter
    labels:
      - "traefik.enable=false"

  master-cadvisor:
    extends:
      file: docker-compose.yml
      service: master-cadvisor
    labels:
      - "traefik.enable=false"

  prometheus:
    extends:
      file: docker-compose.yml
      service: prometheus
    labels:
      - "traefik.enable=true"
      - "traefik.backend=jenkins"
      - "traefik.frontend.rule=Host:prometheus.${DOMAIN}"
      - "traefik.docker.network=monitoring_logging"


  grafana:
    extends:
      file: docker-compose.yml
      service: grafana
    labels:
      - "traefik.enable=true"
      - "traefik.backend=grafana"
      - "traefik.frontend.rule=Host:grafana.${DOMAIN}"
      - "traefik.docker.network=monitoring_logging"

  alertmanager:
    extends:
      file: docker-compose.yml
      service: alertmanager
    labels:
      - "traefik.enable=true"
      - "traefik.backend=alertmanager"
      - "traefik.frontend.rule=Host:alertmanager.${DOMAIN}"
      - "traefik.docker.network=monitoring_logging"

networks:
  default:
    external:
      name: monitoring_logging
