version: '2'

services:
  proxy:
    image: traefik
    command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG --entryPoints='Name:http Address::80 Redirect.EntryPoint:https' --entryPoints='Name:https Address::443 TLS:certs/traefik.crt,certs/traefik.key' --defaultEntryPoints='http,https' --accessLogsFile='log/access.log'
    network_mode: "host"
    ports:
      - "80:80"
      - "8080:8080"
      - "433:433"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#      - ./conf/traefik.toml:/traefik.toml
      - /dev/null:/traefik.toml
      - ./certs:/certs
#    networks:
#      - monitoring_logging
#      - default
#      - webgateway
#    cap_drop:
#      - all
#    cap_add:
#      - net_bind_service
#    webgateway:
#       driver: bridge

#########################################################
####                   Networking                    ####
#########################################################

# Extra-network is necessary to have a dedicated IP for Logstash to forwards log to.
#networks:
#  default:
#    external:
#      name: www_net
#  monitoring_logging:
#    external:
#      name: monitoring_logging
#########################################################
