version: '2'


services:

#########################################################
####                   LIVE                          ####
#########################################################

  # Spins up a Jenkins Instance to build code
  traefik:
    image: traefik
    expose:
      - 80
      - 443
      - 8080
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /dev/null:/traefik.toml
    labels:
      container_group: www
    logging:
      driver: gelf
      options:
        gelf-address: udp://172.42.0.38:12201
        labels: container_group

#########################################################

#########################################################

  # Aggregates logs and forwards them to Elasticsearch.
  logstash:
    image: logstash:5.1.1
    expose:
      - 5044
      - 12201/udp
    volumes:
      - ./logstash/config:/config
      - ./logstash/patterns:/opt/logstash/extra_patterns
    restart: always
    labels:
      container_group: building
    networks:
      default:
        ipv4_address: 172.42.0.38
    logging:
      driver: gelf
      options:
        gelf-address: udp://172.42.0.38:12201
        labels: container_group
    command: logstash -f /config
#########################################################


#########################################################
####                   Networking                    ####
#########################################################

# Extra-network is necessary to have a dedicated IP for Logstash to forwards log to.
networks:
  default:
    external:
      name: www

#########################################################
