version: '2'


services:

########################################################
###                      PROXY                      ####
########################################################

  nginx-proxy:
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/nginx/conf.d
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - ./dockergen/default.vhost:/etc/nginx/vhost.d/default # fixing https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/issues/138
      - ../storage/nginx-proxy/certs:/etc/nginx/certs:ro
      - ../storage/nginx-proxy/htpasswd:/etc/nginx/htpasswd:ro
    labels:
      container_group: proxy
    # logging:
    #   driver: gelf
    #   options:
    #     gelf-address: udp://192.15.0.38:12201
    #     labels: container_group

#########################################################

  nginx-gen:
    image: jwilder/docker-gen
    restart: always
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./dockergen/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
    environment:
      - DEFAULT_HOST="${DOMAIN}"
    command: -notify-sighup nginx-proxy -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    labels:
      container_group: proxy
    # logging:
    #   driver: gelf
    #   options:
    #     gelf-address: udp://192.15.0.38:12201
    #     labels: container_group

#########################################################

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../storage/nginx-proxy/certs:/etc/nginx/certs:rw
    environment:
      - NGINX_DOCKER_GEN_CONTAINER="nginx-gen"
    labels:
      container_group: proxy
    # logging:
    #   driver: gelf
    #   options:
    #     gelf-address: udp://192.15.0.38:12201
    #     labels: container_group
    environment:
      - DEBUG=false

#########################################################
####                   Networking                    ####
#########################################################

# Extra-network is necessary to have a dedicated IP for Logstash to forwards log to.
networks:
  default:
    external:
      name: monitoring_logging
