version: '2'


services:

#########################################################
####                   BUILDING                      ####
#########################################################

  # Spins up a Jenkins Instance to build code
  jenkins:
    image: jenkins
    expose:
      - 8080
      - 50000
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /usr/bin/docker:/usr/bin/docker
      - /usr/bin/make:/usr/bin/make
      - ../storage/jenkins:/var/jenkins_home
    labels:
      container_group: building
      - "traefik.enable=true"
      - "traefik.backend=jenkins"
      - "traefik.frontend.rule=Host:jenkins.${DOMAIN}"
      - "traefik.docker.network=building_net"
      - "traefik.port=8080"

    logging:
      driver: gelf
      options:
        gelf-address: udp://172.16.0.38:12201
        labels: container_group

#########################################################

  # Runs a sonarqube to keep track of your l33t skillz
  sonarqube:
    image: sonarqube:alpine
    expose:
      - 9000
    restart: always
    labels:
      container_group: building
      - "traefik.enable=true"
      - "traefik.backend=sonarqube"
      - "traefik.frontend.rule=Host:sonarqube.${DOMAIN}"
      - "traefik.docker.network=building_net"

    volumes:
      - ../storage/sonarqube:/data
    environment:
      - SONARQUBE_HOME=/data
    networks:
      default:
        ipv4_address: 172.24.0.42

    logging:
      driver: gelf
      options:
        gelf-address: udp://172.24.0.38:12201
        labels: container_group

#########################################################

#########################################################

  # Runs a sonar-scanner of your app
  sonarscan:
    image: mercuriete/sonar-scanner
    restart: always
    labels:
      container_group: building
    volumes:
      - ../storage/app:/usr/src
    environment:
      - SONAR_HOST_URL=http://172.24.0.42:9000
      - SONAR_PROJECT_KEY=hello:world
      - SONAR_PROJECT_NAME=HelloWorld
      - SONAR_PROJECT_VERSION=0.1
    networks:
      default:
    depends_on:
      - sonarqube
    labels:
      - "traefik.enable=false"

    logging:
      driver: gelf
      options:
        gelf-address: udp://172.24.0.38:12201
        labels: container_group

#########################################################
####                   Networking                    ####
#########################################################

# Extra-network is necessary to have a dedicated IP for Logstash to forwards log to.
networks:
  default:
    external:
      name: building_net

#########################################################
