version: '2'


services:

  jenkins:
    extends:
      file: docker-compose.yml
      service: jenkins
    ports:
      - 8090:8080

  sonarqube:
    extends:
      file: docker-compose.yml
      service: sonarqube
    ports:
      - 9000:9000
  sonarscan:
    extends:
      file: docker-compose.yml
      service: sonarscan
  logstash:
    extends:
      file: docker-compose.yml
      service: logstash


networks:
  default:
    external:
      name: building
