version: '2'


services:

  jenkins:
    extends:
      file: docker-compose.yml
      service: jenkins
    labels:
      - "traefik.enable=true"
      - "traefik.backend=jenkins"
      - "traefik.frontend.rule=Host:jenkins.${DOMAIN}"
      - "traefik.docker.network=building_net"

  sonarqube:
    extends:
      file: docker-compose.yml
      service: sonarqube
    labels:
      - "traefik.enable=true"
      - "traefik.backend=sonarqube"
      - "traefik.frontend.rule=Host:sonarqube.${DOMAIN}"
      - "traefik.docker.network=building_net"

  sonarscan:
    extends:
        file: docker-compose.yml
        service: sonarscan
    labels:
      - "traefik.enable=false"


networks:
  default:
    external:
      name: building_net
